build:
  image: stormenroute/storm-enroute-build:0.1
  commands:
    - mkdir -p ~/.ssh
    - echo $$SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - echo $$SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
    - echo "pull request no. $DRONE_PULL_REQUEST"
    - if [ "$DRONE_PULL_REQUEST" != "" ]; then (sbt test); else (sbt mecha-nightly); fi
